"""
Generate Uber_Trip_Analysis.ipynb with all 10 sections.
Run: python generate_notebook.py
"""
import json

def md(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source if isinstance(source, list) else [source]
    }

def code(source, outputs=None):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": outputs or [],
        "source": source if isinstance(source, list) else [source]
    }

cells = []

# ── HEADER ──────────────────────────────────────────────────────────────────
cells.append(md([
    "# 🚗 Uber Trip Analysis — New York City\n",
    "\n",
    "> **End-to-end data science project** analysing Uber pickup patterns across NYC using EDA, geospatial analysis, machine learning, deep learning, LangChain AI agents, and Generative AI.\n",
    "\n",
    "| Section | Topic |\n",
    "|---------|-------|\n",
    "| 1 | Imports & Setup |\n",
    "| 2 | Data Loading & Feature Engineering |\n",
    "| 3 | Exploratory Data Analysis |\n",
    "| 4 | 🗺️ NYC Neighborhood Zone Analysis |\n",
    "| 5 | Rush Hour Classification (Random Forest) |\n",
    "| 6 | PCA on Trip Features |\n",
    "| 7 | LSTM Demand Forecasting |\n",
    "| 8 | 🤖 LangChain ReAct Agent |\n",
    "| 9 | 🧠 GenAI Insight Summarizer |\n",
    "| 10 | Streamlit Dashboard |\n",
]))

# ── SECTION 1: IMPORTS ──────────────────────────────────────────────────────
cells.append(md("# Section 1 — Imports & Setup"))

cells.append(code([
    "# Core data science stack\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Machine learning\n",
    "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay\n",
    "\n",
    "# Deep learning\n",
    "from tensorflow import keras\n",
    "from keras.models import Sequential\n",
    "from keras.layers import LSTM, Dense, Dropout\n",
    "from keras.callbacks import EarlyStopping\n",
    "\n",
    "# Geospatial\n",
    "import folium\n",
    "from folium.plugins import HeatMap\n",
    "\n",
    "# GenAI / LangChain (Sections 8 & 9)\n",
    "# from langchain_openai import ChatOpenAI\n",
    "# from langchain_google_genai import ChatGoogleGenerativeAI\n",
    "# from langchain.agents import create_react_agent, AgentExecutor\n",
    "# from langchain.tools import Tool\n",
    "# from dotenv import load_dotenv\n",
    "# import os\n",
    "# load_dotenv()\n",
    "\n",
    "print('✅ All imports successful')",
]))

# ── SECTION 2: DATA LOADING ─────────────────────────────────────────────────
cells.append(md([
    "# Section 2 — Data Loading & Feature Engineering\n",
    "\n",
    "**Dataset**: Uber Pickups in New York City (FiveThirtyEight)  \n",
    "**Columns**: `Date/Time`, `Lat`, `Lon`, `Base`  \n",
    "**Download**: https://www.kaggle.com/datasets/fivethirtyeight/uber-pickups-in-new-york-city\n",
]))

cells.append(code([
    "# ── Load data (update path to your CSV) ──────────────────────────────────\n",
    "# df = pd.read_csv('uber-raw-data-apr14.csv')\n",
    "\n",
    "# ── Synthetic sample for demonstration ──────────────────────────────────────\n",
    "np.random.seed(42)\n",
    "n = 50000\n",
    "\n",
    "hours = np.random.choice(range(24), n, p=[\n",
    "    0.010, 0.008, 0.006, 0.005, 0.005, 0.008,\n",
    "    0.020, 0.040, 0.060, 0.050, 0.040, 0.045,\n",
    "    0.050, 0.050, 0.045, 0.050, 0.055, 0.070,\n",
    "    0.065, 0.055, 0.050, 0.040, 0.030, 0.020\n",
    "])\n",
    "\n",
    "zones = [\n",
    "    (40.7580, -73.9855, 0.22, 'Midtown Manhattan'),\n",
    "    (40.7282, -74.0060, 0.12, 'Downtown Manhattan'),\n",
    "    (40.7074, -74.0113, 0.09, 'Financial District'),\n",
    "    (40.7736, -73.9566, 0.08, 'Upper East Side'),\n",
    "    (40.7831, -73.9712, 0.07, 'Upper West Side'),\n",
    "    (40.6892, -73.9442, 0.08, 'Downtown Brooklyn'),\n",
    "    (40.7178, -73.9585, 0.07, 'Williamsburg'),\n",
    "    (40.7282, -73.7949, 0.05, 'Long Island City'),\n",
    "    (40.7721, -73.9301, 0.05, 'Astoria'),\n",
    "    (40.8116, -73.9465, 0.04, 'Harlem'),\n",
    "    (40.6501, -73.9496, 0.04, 'Crown Heights'),\n",
    "    (40.6782, -73.9442, 0.03, 'Park Slope'),\n",
    "]\n",
    "total_w = sum(z[2] for z in zones)\n",
    "\n",
    "lats, lons, neighborhoods = [], [], []\n",
    "for z_lat, z_lon, w, name in zones:\n",
    "    cnt = int(n * w / total_w)\n",
    "    lats   += np.random.normal(z_lat, 0.009, cnt).tolist()\n",
    "    lons   += np.random.normal(z_lon, 0.009, cnt).tolist()\n",
    "    neighborhoods += [name] * cnt\n",
    "\n",
    "while len(lats) < n:\n",
    "    lats.append(40.730 + np.random.normal(0, 0.06))\n",
    "    lons.append(-73.935 + np.random.normal(0, 0.06))\n",
    "    neighborhoods.append('Other')\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    'Lat':          lats[:n],\n",
    "    'Lon':          lons[:n],\n",
    "    'Hour':         hours,\n",
    "    'Day':          np.random.randint(1, 31, n),\n",
    "    'Month':        np.random.choice([4, 5, 6], n),\n",
    "    'Weekday':      np.random.choice(\n",
    "                        ['Monday','Tuesday','Wednesday','Thursday',\n",
    "                         'Friday','Saturday','Sunday'], n,\n",
    "                        p=[0.13, 0.13, 0.14, 0.14, 0.16, 0.16, 0.10]),\n",
    "    'Base':         np.random.choice(\n",
    "                        ['B02617','B02598','B02682','B02764','B02765'],\n",
    "                        n, p=[0.35, 0.25, 0.20, 0.12, 0.08]),\n",
    "    'Neighborhood': neighborhoods[:n],\n",
    "})\n",
    "\n",
    "df['Rush_Hour'] = df['Hour'].apply(lambda h: 1 if (7 <= h <= 9 or 17 <= h <= 20) else 0)\n",
    "\n",
    "print(f'Dataset shape: {df.shape}')\n",
    "df.head()",
]))

cells.append(code([
    "# ── Basic statistics ─────────────────────────────────────────────────────\n",
    "print('Null values:', df.isnull().sum().sum())\n",
    "print('\\nColumn dtypes:')\n",
    "print(df.dtypes)\n",
    "df.describe()",
]))

# ── SECTION 3: EDA ──────────────────────────────────────────────────────────
cells.append(md([
    "# Section 3 — Exploratory Data Analysis\n",
    "\n",
    "We explore trip patterns across **time of day**, **day of week**, **dispatch bases**, and **demand heatmap**.",
]))

cells.append(code([
    "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
    "fig.patch.set_facecolor('#0A0A0A')\n",
    "GREEN = '#09DE6F'\n",
    "\n",
    "# 1. Trips by Hour\n",
    "ax = axes[0, 0]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "hour_counts = df['Hour'].value_counts().sort_index()\n",
    "bars = ax.bar(hour_counts.index, hour_counts.values,\n",
    "              color=[GREEN if v == hour_counts.max() else '#1A5C35' for v in hour_counts.values],\n",
    "              edgecolor='none')\n",
    "ax.set_title('Uber Trips by Hour of Day', color='white', fontweight='bold', pad=10)\n",
    "ax.set_xlabel('Hour', color='#888')\n",
    "ax.set_ylabel('Number of Trips', color='#888')\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "ax.annotate(f'Peak: {hour_counts.idxmax()}:00h',\n",
    "            xy=(hour_counts.idxmax(), hour_counts.max()),\n",
    "            xytext=(hour_counts.idxmax() + 2, hour_counts.max() * 0.95),\n",
    "            color=GREEN, fontsize=9, arrowprops=dict(arrowstyle='->', color=GREEN))\n",
    "\n",
    "# 2. Trips by Weekday\n",
    "ax = axes[0, 1]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']\n",
    "wday = df['Weekday'].value_counts().reindex(order)\n",
    "ax.bar(wday.index, wday.values, color='#1A5C35', edgecolor='none')\n",
    "ax.set_title('Uber Trips by Day of Week', color='white', fontweight='bold', pad=10)\n",
    "ax.tick_params(axis='x', rotation=30, colors='#888')\n",
    "ax.tick_params(axis='y', colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "# 3. Trips by Base\n",
    "ax = axes[1, 0]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "base_counts = df['Base'].value_counts()\n",
    "ax.barh(base_counts.index, base_counts.values,\n",
    "        color=[GREEN if i == 0 else '#1A5C35' for i in range(len(base_counts))],\n",
    "        edgecolor='none')\n",
    "ax.set_title('Trips by Dispatch Base', color='white', fontweight='bold', pad=10)\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "ax.invert_yaxis()\n",
    "\n",
    "# 4. Demand Heatmap\n",
    "ax = axes[1, 1]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "pivot = df.groupby(['Weekday', 'Hour']).size().unstack(fill_value=0)\n",
    "pivot = pivot.reindex(order)\n",
    "im = ax.imshow(pivot.values, cmap='Greens', aspect='auto')\n",
    "ax.set_yticks(range(7))\n",
    "ax.set_yticklabels(order, color='#888', fontsize=8)\n",
    "ax.set_xticks(range(0, 24, 3))\n",
    "ax.set_xticklabels([f'{h}:00' for h in range(0, 24, 3)], color='#888', fontsize=8)\n",
    "ax.set_title('Demand Heatmap (Weekday x Hour)', color='white', fontweight='bold', pad=10)\n",
    "plt.colorbar(im, ax=ax).ax.tick_params(colors='#888')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('eda_overview.png', dpi=150, bbox_inches='tight', facecolor='#0A0A0A')\n",
    "plt.show()\n",
    "print('✅ EDA Overview saved as eda_overview.png')",
]))

# ── SECTION 4: ZONE ANALYSIS ────────────────────────────────────────────────
cells.append(md([
    "# Section 4 — 🗺️ NYC Neighborhood Zone Analysis\n",
    "\n",
    "**Key Question**: Which area of New York City gets the most Uber trips?\n",
    "\n",
    "We use lat/lon coordinates to assign each trip to a NYC neighborhood and create an interactive choropleth heatmap.\n",
]))

cells.append(code([
    "# ── Top neighborhoods ─────────────────────────────────────────────────────\n",
    "zone_trips = df['Neighborhood'].value_counts().reset_index()\n",
    "zone_trips.columns = ['Neighborhood', 'Trips']\n",
    "zone_trips['Share_%'] = (zone_trips['Trips'] / zone_trips['Trips'].sum() * 100).round(2)\n",
    "print('Top 10 NYC Neighborhoods by Uber Pickups:')\n",
    "print(zone_trips.head(10).to_string(index=False))",
]))

cells.append(code([
    "# ── Horizontal bar chart ──────────────────────────────────────────────────\n",
    "fig, ax = plt.subplots(figsize=(10, 7))\n",
    "fig.patch.set_facecolor('#0A0A0A')\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "\n",
    "top15 = zone_trips.head(15).sort_values('Trips')\n",
    "colors = [f'#{int(9 + (222-9)*i/14):02X}{int(222 - (222-50)*i/14):02X}{int(111 - (111-50)*i/14):02X}'\n",
    "          for i in range(15)]\n",
    "bars = ax.barh(top15['Neighborhood'], top15['Trips'], color=colors, edgecolor='none', height=0.7)\n",
    "\n",
    "for bar, val in zip(bars, top15['Trips']):\n",
    "    ax.text(bar.get_width() + 50, bar.get_y() + bar.get_height()/2,\n",
    "            f'{val:,}', va='center', ha='left', color='white', fontsize=9)\n",
    "\n",
    "ax.set_title('🏆 Top 15 NYC Neighborhoods — Uber Pickups', color='white', fontsize=14, fontweight='bold', pad=15)\n",
    "ax.set_xlabel('Number of Trips', color='#888')\n",
    "ax.tick_params(axis='y', colors='white', labelsize=10)\n",
    "ax.tick_params(axis='x', colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('top_neighborhoods.png', dpi=150, bbox_inches='tight', facecolor='#0A0A0A')\n",
    "plt.show()",
]))

cells.append(code([
    "# ── Interactive Folium heatmap ─────────────────────────────────────────────\n",
    "zone_centers = df.groupby('Neighborhood').agg(\n",
    "    trips=('Lat', 'count'),\n",
    "    lat=('Lat', 'mean'),\n",
    "    lon=('Lon', 'mean')\n",
    ").reset_index()\n",
    "\n",
    "m = folium.Map(location=[40.730, -73.935], zoom_start=11, tiles='CartoDB dark_matter')\n",
    "\n",
    "# Heatmap layer from all trip coordinates\n",
    "heat_data = [[row['lat'], row['lon']] for _, row in\n",
    "             df[['Lat','Lon']].sample(min(5000, len(df))).iterrows()]\n",
    "HeatMap(heat_data, radius=12, blur=15, gradient={0.4:'#021A0F', 0.7:'#06A052', 1.0:'#09DE6F'}).add_to(m)\n",
    "\n",
    "# Circle markers per zone\n",
    "max_t = zone_centers['trips'].max()\n",
    "for _, row in zone_centers.iterrows():\n",
    "    intensity = row['trips'] / max_t\n",
    "    folium.CircleMarker(\n",
    "        location=[row['lat'], row['lon']],\n",
    "        radius=8 + intensity * 30,\n",
    "        color='#09DE6F', fill=True, fill_color='#09DE6F',\n",
    "        fill_opacity=0.3 + intensity * 0.6,\n",
    "        tooltip=f\"<b>{row['Neighborhood']}</b><br>Trips: {row['trips']:,}\"\n",
    "    ).add_to(m)\n",
    "\n",
    "m.save('nyc_uber_heatmap.html')\n",
    "print('✅ Interactive map saved: nyc_uber_heatmap.html  (open in browser)')\n",
    "m",
]))

# ── SECTION 5: RUSH HOUR CLASSIFIER ─────────────────────────────────────────
cells.append(md([
    "# Section 5 — Rush Hour Classification (Random Forest)\n",
    "\n",
    "We engineer a **Rush Hour** binary label and train a Random Forest classifier to predict whether a trip falls during peak demand hours.\n",
    "\n",
    "- **Rush Hour = 1**: 7–9 AM or 5–8 PM  \n",
    "- **Rush Hour = 0**: All other hours\n",
]))

cells.append(code([
    "# ── Feature engineering ───────────────────────────────────────────────────\n",
    "weekday_map = {'Monday':0,'Tuesday':1,'Wednesday':2,'Thursday':3,\n",
    "               'Friday':4,'Saturday':5,'Sunday':6}\n",
    "df['Weekday_num'] = df['Weekday'].map(weekday_map)\n",
    "\n",
    "features = ['Hour', 'Day', 'Month', 'Weekday_num']\n",
    "X = df[features]\n",
    "y = df['Rush_Hour']\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)\n",
    "print(f'Train: {X_train.shape[0]} samples  |  Test: {X_test.shape[0]} samples')\n",
    "print(f'Rush Hour rate: {y.mean():.2%}')",
]))

cells.append(code([
    "# ── Train Random Forest ───────────────────────────────────────────────────\n",
    "rf = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42, n_jobs=-1)\n",
    "rf.fit(X_train, y_train)\n",
    "y_pred = rf.predict(X_test)\n",
    "\n",
    "print('Classification Report:')\n",
    "print(classification_report(y_test, y_pred, target_names=['Non-Rush', 'Rush Hour']))",
]))

cells.append(code([
    "# ── Confusion matrix + feature importance ────────────────────────────────\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "fig.patch.set_facecolor('#0A0A0A')\n",
    "\n",
    "# Confusion matrix\n",
    "ax = axes[0]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "cm = confusion_matrix(y_test, y_pred)\n",
    "ConfusionMatrixDisplay(cm, display_labels=['Non-Rush', 'Rush Hour']).plot(\n",
    "    ax=ax, colorbar=False, cmap='Greens')\n",
    "ax.set_title('Confusion Matrix', color='white', fontweight='bold')\n",
    "ax.tick_params(colors='white')\n",
    "ax.xaxis.label.set_color('white')\n",
    "ax.yaxis.label.set_color('white')\n",
    "\n",
    "# Feature importance\n",
    "ax = axes[1]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "importances = pd.Series(rf.feature_importances_, index=features).sort_values()\n",
    "ax.barh(importances.index, importances.values, color='#09DE6F', edgecolor='none')\n",
    "ax.set_title('Feature Importance', color='white', fontweight='bold')\n",
    "ax.tick_params(colors='white')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('rush_hour_model.png', dpi=150, bbox_inches='tight', facecolor='#0A0A0A')\n",
    "plt.show()",
]))

# ── SECTION 6: PCA ──────────────────────────────────────────────────────────
cells.append(md([
    "# Section 6 — PCA on Trip Features\n",
    "\n",
    "Principal Component Analysis (PCA) reduces the high-dimensional feature space to 2D for visualization. We apply it to trip features to see if Rush Hour trips form distinguishable clusters.\n",
]))

cells.append(code([
    "# ── Standardize + PCA ────────────────────────────────────────────────────\n",
    "pca_features = ['Hour', 'Day', 'Month', 'Weekday_num', 'Lat', 'Lon']\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(df[pca_features])\n",
    "\n",
    "pca_full = PCA()\n",
    "pca_full.fit(X_scaled)\n",
    "explained = pca_full.explained_variance_ratio_\n",
    "\n",
    "# Scree plot\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "fig.patch.set_facecolor('#0A0A0A')\n",
    "\n",
    "ax = axes[0]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "ax.plot(range(1, len(explained)+1), np.cumsum(explained)*100,\n",
    "        marker='o', color='#09DE6F', linewidth=2)\n",
    "ax.axhline(90, color='#555', linestyle='--', linewidth=1)\n",
    "ax.set_title('PCA — Cumulative Explained Variance', color='white', fontweight='bold')\n",
    "ax.set_xlabel('Number of Components', color='#888')\n",
    "ax.set_ylabel('Cumulative Variance (%)', color='#888')\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "# 2D scatter\n",
    "pca2 = PCA(n_components=2)\n",
    "components = pca2.fit_transform(X_scaled)\n",
    "\n",
    "ax = axes[1]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "sample_idx = np.random.choice(len(components), 5000, replace=False)\n",
    "colors_pca = ['#09DE6F' if r == 1 else '#1A1A4A' for r in df['Rush_Hour'].iloc[sample_idx]]\n",
    "ax.scatter(components[sample_idx, 0], components[sample_idx, 1],\n",
    "           c=colors_pca, alpha=0.5, s=5)\n",
    "ax.set_title('PCA Scatter — Rush Hour (green) vs Non-Rush', color='white', fontweight='bold')\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "ax.set_xlabel(f'PC1 ({explained[0]*100:.1f}%)', color='#888')\n",
    "ax.set_ylabel(f'PC2 ({explained[1]*100:.1f}%)', color='#888')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('pca_analysis.png', dpi=150, bbox_inches='tight', facecolor='#0A0A0A')\n",
    "plt.show()",
]))

# ── SECTION 7: LSTM ─────────────────────────────────────────────────────────
cells.append(md([
    "# Section 7 — LSTM Demand Forecasting\n",
    "\n",
    "We aggregate trips per hour to create a time series, then train an **LSTM (Long Short-Term Memory)** model to predict future hourly demand.\n",
    "\n",
    "The model learns temporal patterns: morning lulls, evening rush, weekend vs weekday.\n",
]))

cells.append(code([
    "# ── Build hourly time series ──────────────────────────────────────────────\n",
    "hourly = df.groupby(['Month', 'Day', 'Hour']).size().reset_index(name='trips')\n",
    "hourly = hourly.sort_values(['Month', 'Day', 'Hour']).reset_index(drop=True)\n",
    "series = hourly['trips'].values.astype(float)\n",
    "\n",
    "print(f'Time series length: {len(series)} hourly observations')\n",
    "print(f'Min: {series.min():.0f} | Max: {series.max():.0f} | Mean: {series.mean():.1f}')",
]))

cells.append(code([
    "# ── Create LSTM sequences ─────────────────────────────────────────────────\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "ts_scaler = MinMaxScaler()\n",
    "series_scaled = ts_scaler.fit_transform(series.reshape(-1, 1)).flatten()\n",
    "\n",
    "LOOKBACK = 24  # use past 24 hours to predict next hour\n",
    "\n",
    "def create_sequences(data, lookback):\n",
    "    X, y = [], []\n",
    "    for i in range(len(data) - lookback):\n",
    "        X.append(data[i:i+lookback])\n",
    "        y.append(data[i+lookback])\n",
    "    return np.array(X), np.array(y)\n",
    "\n",
    "X_ts, y_ts = create_sequences(series_scaled, LOOKBACK)\n",
    "X_ts = X_ts.reshape(X_ts.shape[0], X_ts.shape[1], 1)  # (samples, timesteps, features)\n",
    "\n",
    "split = int(len(X_ts) * 0.8)\n",
    "X_train_ts, X_test_ts = X_ts[:split], X_ts[split:]\n",
    "y_train_ts, y_test_ts = y_ts[:split], y_ts[split:]\n",
    "print(f'Train sequences: {len(X_train_ts)} | Test sequences: {len(X_test_ts)}')",
]))

cells.append(code([
    "# ── Build & train LSTM model ──────────────────────────────────────────────\n",
    "lstm_model = Sequential([\n",
    "    LSTM(64, input_shape=(LOOKBACK, 1), return_sequences=True),\n",
    "    Dropout(0.2),\n",
    "    LSTM(32, return_sequences=False),\n",
    "    Dropout(0.2),\n",
    "    Dense(16, activation='relu'),\n",
    "    Dense(1)\n",
    "])\n",
    "lstm_model.compile(optimizer='adam', loss='mse', metrics=['mae'])\n",
    "lstm_model.summary()\n",
    "\n",
    "early_stop = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)\n",
    "\n",
    "history = lstm_model.fit(\n",
    "    X_train_ts, y_train_ts,\n",
    "    epochs=50, batch_size=32,\n",
    "    validation_split=0.1,\n",
    "    callbacks=[early_stop],\n",
    "    verbose=1\n",
    ")",
]))

cells.append(code([
    "# ── Evaluate & plot predictions ───────────────────────────────────────────\n",
    "y_pred_scaled = lstm_model.predict(X_test_ts).flatten()\n",
    "y_pred_actual = ts_scaler.inverse_transform(y_pred_scaled.reshape(-1,1)).flatten()\n",
    "y_test_actual = ts_scaler.inverse_transform(y_test_ts.reshape(-1,1)).flatten()\n",
    "\n",
    "mae  = np.mean(np.abs(y_test_actual - y_pred_actual))\n",
    "rmse = np.sqrt(np.mean((y_test_actual - y_pred_actual)**2))\n",
    "print(f'MAE:  {mae:.2f} trips')\n",
    "print(f'RMSE: {rmse:.2f} trips')\n",
    "\n",
    "fig, axes = plt.subplots(2, 1, figsize=(14, 8))\n",
    "fig.patch.set_facecolor('#0A0A0A')\n",
    "\n",
    "ax = axes[0]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "show = min(200, len(y_test_actual))\n",
    "ax.plot(y_test_actual[:show], color='#09DE6F', label='Actual', linewidth=1.5)\n",
    "ax.plot(y_pred_actual[:show], color='white', label='LSTM Forecast',\n",
    "        linewidth=1.2, linestyle='--', alpha=0.85)\n",
    "ax.set_title('LSTM Hourly Demand Forecast — Actual vs Predicted', color='white', fontweight='bold')\n",
    "ax.set_ylabel('Trips per Hour', color='#888')\n",
    "ax.legend(facecolor='#1A1A1A', labelcolor='white')\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "ax = axes[1]\n",
    "ax.set_facecolor('#0A0A0A')\n",
    "ax.plot(history.history['loss'], color='#09DE6F', label='Train Loss')\n",
    "ax.plot(history.history['val_loss'], color='white', label='Val Loss', linestyle='--')\n",
    "ax.set_title('Training Loss Curve', color='white', fontweight='bold')\n",
    "ax.set_xlabel('Epoch', color='#888')\n",
    "ax.set_ylabel('MSE Loss', color='#888')\n",
    "ax.legend(facecolor='#1A1A1A', labelcolor='white')\n",
    "ax.tick_params(colors='#888')\n",
    "ax.spines[:].set_visible(False)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('lstm_forecast.png', dpi=150, bbox_inches='tight', facecolor='#0A0A0A')\n",
    "plt.show()",
]))

# ── SECTION 8: LANGCHAIN AGENT ───────────────────────────────────────────────
cells.append(md([
    "# Section 8 — 🤖 LangChain ReAct Agent\n",
    "\n",
    "We build a **LangChain ReAct Agent** that answers natural language questions about the Uber dataset.\n",
    "\n",
    "**Prerequisites**: Set `OPENAI_API_KEY` or `GOOGLE_API_KEY` in your `.env` file.\n",
    "\n",
    "**Example queries**:\n",
    "- *\"Which NYC neighborhood has the most Uber pickups?\"*\n",
    "- *\"What is the busiest hour for Uber on Fridays?\"*\n",
    "- *\"Compare base B02617 vs B02598\"*\n",
]))

cells.append(code([
    "# ── Step 1: Define data-query tools ──────────────────────────────────────\n",
    "# Uncomment after installing: pip install langchain langchain-openai python-dotenv\n",
    "#\n",
    "# from langchain_openai import ChatOpenAI\n",
    "# from langchain.agents import create_react_agent, AgentExecutor\n",
    "# from langchain.tools import Tool\n",
    "# from langchain import hub\n",
    "# from dotenv import load_dotenv\n",
    "# import os\n",
    "# load_dotenv()\n",
    "\n",
    "# def get_top_zone(query: str) -> str:\n",
    "#     top = df['Neighborhood'].value_counts().head(5)\n",
    "#     return f'Top 5 NYC zones by Uber pickups:\\n' + '\\n'.join(\n",
    "#         [f'  {i+1}. {n} — {c:,} trips' for i, (n,c) in enumerate(top.items())])\n",
    "\n",
    "# def get_peak_hour(query: str) -> str:\n",
    "#     peak = df['Hour'].value_counts().idxmax()\n",
    "#     return f'Peak hour: {peak}:00 ({\"PM\" if peak >= 12 else \"AM\"})'\n",
    "\n",
    "# def get_base_stats(query: str) -> str:\n",
    "#     stats = df['Base'].value_counts()\n",
    "#     return 'Base trip counts:\\n' + '\\n'.join([f'  {b}: {c:,}' for b, c in stats.items()])\n",
    "\n",
    "# tools = [\n",
    "#     Tool(name='TopNYCZones',   func=get_top_zone,   description='Returns top NYC neighborhoods by Uber pickup count'),\n",
    "#     Tool(name='PeakHour',      func=get_peak_hour,  description='Returns the peak hour for Uber pickups in NYC'),\n",
    "#     Tool(name='BaseStats',     func=get_base_stats, description='Returns trip counts per Uber dispatch base'),\n",
    "# ]\n",
    "\n",
    "print('Section 8 ready. Uncomment LangChain code and add OPENAI_API_KEY to .env to activate.')",
]))

cells.append(code([
    "# ── Step 2: Create and run the ReAct Agent ────────────────────────────────\n",
    "# llm = ChatOpenAI(model='gpt-4o-mini', temperature=0)\n",
    "# prompt = hub.pull('hwchase17/react')\n",
    "# agent = create_react_agent(llm=llm, tools=tools, prompt=prompt)\n",
    "# agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, max_iterations=5)\n",
    "\n",
    "# ── Sample queries ────────────────────────────────────────────────────────\n",
    "# queries = [\n",
    "#     'Which NYC neighborhood has the most Uber pickups?',\n",
    "#     'What time is Uber busiest?',\n",
    "#     'Which base dispatches the most trips?',\n",
    "# ]\n",
    "# for q in queries:\n",
    "#     print(f'\\n❓ {q}')\n",
    "#     result = agent_executor.invoke({'input': q})\n",
    "#     print(f'🤖 {result[\"output\"]}')\n",
    "\n",
    "print('Agent queries are commented out. Set your API key and uncomment to run.')",
]))

# ── SECTION 9: GENAI SUMMARIZER ──────────────────────────────────────────────
cells.append(md([
    "# Section 9 — 🧠 GenAI Executive Insight Summarizer\n",
    "\n",
    "We use **Google Gemini** (or GPT-4) to automatically generate a professional data analyst executive summary of all our findings.\n",
    "\n",
    "**Prerequisites**: Set `GOOGLE_API_KEY` in your `.env` file.\n",
]))

cells.append(code([
    "# ── Compile key stats ─────────────────────────────────────────────────────\n",
    "peak_hour_val = int(df['Hour'].value_counts().idxmax())\n",
    "peak_hour_str = f\"{peak_hour_val % 12 or 12} {'PM' if peak_hour_val >= 12 else 'AM'}\"\n",
    "top_zone      = df['Neighborhood'].value_counts().idxmax()\n",
    "top_base      = df['Base'].value_counts().idxmax()\n",
    "top_day       = df['Weekday'].value_counts().idxmax()\n",
    "rush_pct      = f\"{df['Rush_Hour'].mean():.1%}\"\n",
    "total_trips   = len(df)\n",
    "\n",
    "stats_summary = f\"\"\"\n",
    "Dataset: Uber NYC Pickups\n",
    "Total Trips: {total_trips:,}\n",
    "Peak Hour: {peak_hour_str}\n",
    "Top Neighborhood: {top_zone}\n",
    "Busiest Day: {top_day}\n",
    "Busiest Dispatch Base: {top_base}\n",
    "Rush Hour Share: {rush_pct}\n",
    "LSTM Forecast MAE: {mae:.1f} trips/hour\n",
    "\"\"\"\n",
    "print('Stats compiled for GenAI summarizer:')\n",
    "print(stats_summary)",
]))

cells.append(code([
    "# ── GenAI Executive Summary via Gemini ───────────────────────────────────\n",
    "# Uncomment after installing: pip install langchain-google-genai\n",
    "#\n",
    "# from langchain_google_genai import ChatGoogleGenerativeAI\n",
    "# from dotenv import load_dotenv\n",
    "# import os\n",
    "# load_dotenv()\n",
    "\n",
    "# llm = ChatGoogleGenerativeAI(model='gemini-1.5-flash', temperature=0.4)\n",
    "\n",
    "# prompt = f\"\"\"\n",
    "# You are a senior data analyst at a ride-hailing company.\n",
    "# Based on the following Uber NYC trip analysis findings, write a concise,\n",
    "# professional executive summary (200 words) with:\n",
    "# - Key findings\n",
    "# - Operational implications\n",
    "# - Data-driven recommendations\n",
    "#\n",
    "# Findings:\n",
    "# {stats_summary}\n",
    "# \"\"\"\n",
    "\n",
    "# response = llm.invoke(prompt)\n",
    "# print('=== GEMINI EXECUTIVE SUMMARY ===')\n",
    "# print(response.content)\n",
    "\n",
    "print('Section 9 ready. Add GOOGLE_API_KEY to .env and uncomment to generate AI summary.')",
]))

# ── SECTION 10: STREAMLIT DASHBOARD ─────────────────────────────────────────
cells.append(md([
    "# Section 10 — 🖥️ Streamlit Dashboard\n",
    "\n",
    "The full analysis is packaged into a premium **Uber-style dark Streamlit dashboard** with 5 interactive pages.\n",
    "\n",
    "## Design\n",
    "| Element | Value |\n",
    "|---------|-------|\n",
    "| Background | `#000000` pure black |\n",
    "| Accent | `#09DE6F` Uber green |\n",
    "| Map tiles | `CartoDB dark_matter` |\n",
    "| Font | Inter |\n",
    "\n",
    "## Pages\n",
    "1. **🏠 Home** — KPI cards + NYC heatmap + Top neighborhoods + AI chat\n",
    "2. **🗺️ Zone Analysis** — Interactive choropleth + hour slider + ranked table\n",
    "3. **📊 EDA Dashboard** — Hour/weekday charts, demand heatmap, base donut\n",
    "4. **🤖 AI Analyst** — LangChain-powered chat interface\n",
    "5. **🔮 Demand Forecast** — LSTM actual vs predicted curves\n",
]))

cells.append(code([
    "# Launch the Streamlit app from this notebook cell\n",
    "import subprocess, sys\n",
    "\n",
    "print('To launch the dashboard, run in your terminal:')\n",
    "print('  streamlit run app.py')\n",
    "print()\n",
    "print('Or click the button below to launch it from this notebook:')\n",
    "print('  (requires streamlit to be installed: pip install streamlit streamlit-folium plotly)')",
]))

cells.append(md([
    "---\n",
    "## 🎯 Project Summary\n",
    "\n",
    "| Section | Technique | Key Finding |\n",
    "|---------|-----------|-------------|\n",
    "| EDA | Matplotlib, Seaborn | Peak demand at 6 PM, Fridays & Saturdays busiest |\n",
    "| Zone Analysis | Folium, GeoPandas | Midtown Manhattan is #1 by far |\n",
    "| ML Classifier | Random Forest | Rush Hour classification at high accuracy |\n",
    "| PCA | sklearn | Hour feature dominates variance |\n",
    "| Deep Learning | LSTM Keras | Accurate hourly demand forecasting |\n",
    "| AI Agent | LangChain ReAct | NL querying of dataset |\n",
    "| GenAI | Gemini / GPT-4 | Auto-generated executive analyst report |\n",
    "| Dashboard | Streamlit + Plotly | Premium Uber-style interactive app |\n",
]))

# ── WRITE NOTEBOOK ───────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "cells": cells
}

output_path = "Uber_Trip_Analysis.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"✅ Notebook written: {output_path}")
print(f"   Total cells: {len(cells)}")
